### ISSUE TITLE
Investigate possiblity to modify copies of sheets on Execom G Suite

### ISSUE THREAD

**Issue by BMatijasevicExecom** [execom-eu/exebite#110]
Currently there is no way to modify Google Sheets within Execom G Suite. Only possibility is to copy them to some account outside of Execom G Suite. Investigate if it is possible to allow modifications of Google Sheet copies even within Execom G Suite while preserving the rule that original Sheets cannot be edited (at least not before release is created).

**Comment by Desomph** [comment]
From my experience, you cannot edit the sheets you're not permitted to - in this case the food sheets created by administration. You can, however, create a copy of the sheets with your Execom G Suite account and make changes to the copies.

**Comment by BMatijasevicExecom** [comment]
> 
> 
> From my experience, you cannot edit the sheets you're not permitted to - in this case the food sheets created by administration. You can, however, create a copy of the sheets with your Execom G Suite account and make changes to the copies.

That is my understanding as well, but I received a report that even copies cannot be edited if your account is under Execom G Suite. This should be investigated and if it is working properly issue should be closed.

**Comment by stanoje** [comment]
> From my experience, you cannot edit the sheets you're not permitted to - in this case the food sheets created by administration. You can, however, create a copy of the sheets with your Execom G Suite account and make changes to the copies.

Technically you can edit the sheets. But please don't :-) 

And yes making the copy is the right choice.  We can consider that sheets , on main account, are production and should not be used for development.

There should not be any, technical, issue regarding the editing the sheets which are under users ownership eg copies.

**Comment by BMatijasevicExecom** [comment]
Closing this one as Exebite application is able to successfully modify copies of Google Sheets even within Execom G Suite personal accounts. Thanks everyone!

As a note, if you are getting "You are trying to edit a protected cell or object" make sure that you have permission to edit cells in your copy of Google Sheets. Permissions for cells and sheets can be found in Tools -> Protect sheet.
